assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: UA-47989707-1

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-paginate

name: Kikstand

permalink: pretty

url: http://www.kikstand.com

future: true
